version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: zxcasd
      POSTGRES_USER: postgres
      POSTGRES_DB: expressts
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    image: typescript-express
    depends_on:
      - db  
    ports:
      - "4000:4000"